version: '2'

services:
  loadbalancer:
    image: xtremgforce/load_balancer
    container_name: loadbalancer
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - constraint:node==master
      - CONSUL_URL=${CONSUL_IP}:8500
    depends_on:
      - green
      - blue
    networks:
      - loadbalancer

  blue:
    image: xtremgforce/nginx-html:1
    container_name: blue
    ports:
      - "80"
    environment:
      - constraint:node==master
      - SERVICE_NAME=blue

  green:
    image: xtremgforce/nginx-html:2
    container_name: green
    ports:
      - "80"
    environment:
      - constraint:node==slave
      - SERVICE_NAME=green

networks:
  loadbalancer:
    driver: overlay

